name: Update Readme Cards

on:
    schedule:
        - cron: "0 3 * * *" # Run every day at 03:00
    push:
        paths:
            - ".github/workflows/readme-cards.yml" # Run any time this file is modified
    workflow_dispatch: # Run manually from the Actions tab

env:
    USERNAME: ${{ github.repository_owner }}

jobs:
    update-readme-cards:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v7

            - name: Generate streak stats
              uses: DenverCoder1/github-readme-streak-stats@main
              with:
                  options: user=${{ github.repository_owner }}&theme=default&disable_animations=true
                  path: profile/readme-cards/streak.svg
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate stats card
              uses: stats-organization/github-readme-stats-action@v2
              with:
                  card: stats
                  options: username=${{ github.repository_owner }}&show_icons=true
                  path: profile/readme-cards/stats.svg
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate top languages card
              uses: stats-organization/github-readme-stats-action@v2
              with:
                  card: top-langs
                  options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&show_icons=true&theme=cobalt
                  path: profile/readme-cards/top-langs.svg
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate WakaTime card
              uses: stats-organization/github-readme-stats-action@v2
              with:
                  card: wakatime
                  options: username=${{ github.repository_owner }}&langs_count=6&show_icons=true&theme=cobalt
                  path: profile/readme-cards/wakatime.svg
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Commit cards
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add profile/readme-cards/*.svg
                  git commit -m "Update README cards" || exit 0
                  git push
